### ISSUE TITLE
GithubApi exception when using kobalt offline

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#105]
Exception in thread "main" java.util.concurrent.ExecutionException: kotlin.TypeCastException: null cannot be cast to non-null type retrofit.mime.TypedByteArray
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.beust.kobalt.Main.run(Main.kt:102)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:48)
	at com.beust.kobalt.MainKt.main(Main.kt:30)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type retrofit.mime.TypedByteArray
	at com.beust.kobalt.misc.GithubApi.parseRetrofitError(GithubApi.kt:40)
	at com.beust.kobalt.misc.GithubApi.access$parseRetrofitError(GithubApi.kt:26)
	at com.beust.kobalt.misc.GithubApi$latestKobaltVersion$callable$1.call(GithubApi.kt:139)
	at com.beust.kobalt.misc.GithubApi$latestKobaltVersion$callable$1.call(GithubApi.kt:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cbeust** [comment]
That's easy to fix, don't go off line.

Just kidding :-)

Will investigate.

**Comment by pabl0rg** [comment]
Hahaha. :)

**Comment by sargunster** [comment]
I also sometimes, but not always, get this on my Travis builds.

https://travis-ci.org/sargunster/CakeParse/builds/105778403#L259

**Comment by cbeust** [comment]
I also notice an NPE at the beginning of the build, can you build with `--log 2` and send me a link to the next travis build that shows this error?

It may or may not be related to the GithubApi problem you're seeing, not sure yet.

**Comment by sargunster** [comment]
Will do.
