### ISSUE TITLE
Exception in thread main

### ISSUE THREAD

**Issue by PaulWoitaschek** [cbeust/kobalt#108]
While building [this Build.kt](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/1578e312e57724b2bd332d71ed15ccf3c3855e45/kobalt/src/Build.kt)

```
Exception in thread "main" kotlin.KotlinNullPointerException
	at com.beust.kobalt.maven.SimpleDep.getVersion(SimpleDep.kt:12)
	at com.beust.kobalt.maven.dependency.MavenDependency.<init>(MavenDependency.kt:30)
	at com.beust.kobalt.maven.DepFactory.create(DepFactory.kt:56)
	at com.beust.kobalt.maven.DepFactory.create$default(DepFactory.kt:29)
	at com.beust.kobalt.maven.dependency.MavenDependency$Companion.create(MavenDependency.kt:57)
	at com.beust.kobalt.maven.dependency.MavenDependency$Companion.create$default(MavenDependency.kt:57)
	at com.beust.kobalt.api.Dependencies.addToDependencies(Project.kt:144)
	at com.beust.kobalt.api.Dependencies.compile(Project.kt:150)
	at Kobalt927438457356390478Kt$p$1$3.invoke(kobalt927438457356390478.kt:37)
	at Kobalt927438457356390478Kt$p$1$3.invoke(kobalt927438457356390478.kt)
	at com.beust.kobalt.api.Project.dependencies(Project.kt:81)
	at Kobalt927438457356390478Kt$p$1.invoke(kobalt927438457356390478.kt:30)
	at Kobalt927438457356390478Kt$p$1.invoke(kobalt927438457356390478.kt)
	at com.beust.kobalt.plugin.java.JavaPluginKt.javaProject(JavaPlugin.kt:80)
	at Kobalt927438457356390478Kt.<clinit>(kobalt927438457356390478.kt:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.beust.kobalt.app.BuildScriptUtil.runBuildScriptJarFile(BuildScriptUtil.kt:80)
	at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:89)
	at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:57)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:164)
	at com.beust.kobalt.Main.access$runWithArgs(Main.kt:51)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:88)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:51)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkSeconds(Benchmarks.kt:9)
	at com.beust.kobalt.Main.run(Main.kt:86)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:48)
	at com.beust.kobalt.MainKt.main(Main.kt:30)
  Downloaded http://repo1.maven.org/maven2/com/squareup/retrofit2/adapter-rxjava/2.0.0-beta3/adapter-rxjava-2.0.0-beta3.pom
  Downloaded http://repo1.maven.org/maven2/com/squareup/retrofit2/adapter-rxjava/2.0.0-beta3/adapter-rxjava-2.0.0-beta3.jar
```

**Comment by cbeust** [comment]
I cloned your project but I can’t find any Kobalt file, neither on master nor develop. Can you make sure you pushed everything so I can try and reproduce the problem?
