### ISSUE TITLE
JsonSyntaxException during compile

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#112]
I get this error when i compile, even after running clean

```───── test-project:compile
  Calculating checksum of 909 files in ./src/main/java
  Calculating checksum of 909 files in ./src/main/java
  Calculating checksum of 8 files in ./src/main/kotlin
  Calculating checksum of 8 files in ./src/main/kotlin
  Calculating checksum of 42 files in ./src/main/resources
  Calculating checksum of 42 files in ./src/main/resources
*****
***** ERROR Error: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 8 column 3 path $
*****
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 8 column 3 path $
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.beust.kobalt.internal.DynamicGraphExecutor.run(DynamicGraph.kt:67)
	at com.beust.kobalt.internal.TaskManager.runTargets(TaskManager.kt:176)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:181)
	at com.beust.kobalt.Main.access$runWithArgs(Main.kt:49)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:87)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:49)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkSeconds(Benchmarks.kt:9)
	at com.beust.kobalt.Main.run(Main.kt:85)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:46)
	at com.beust.kobalt.MainKt.main(Main.kt:28)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 8 column 3 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:790)
	at com.google.gson.Gson.fromJson(Gson.java:753)
	at com.beust.kobalt.internal.IncrementalManager.buildInfo(IncrementalManager.kt:32)
	at com.beust.kobalt.internal.IncrementalManager.taskInfos(IncrementalManager.kt:39)
	at com.beust.kobalt.internal.IncrementalManager.inputChecksumFor(IncrementalManager.kt:61)
	at com.beust.kobalt.internal.IncrementalManager$toIncrementalTaskClosure$1.invoke(IncrementalManager.kt:84)
	at com.beust.kobalt.internal.IncrementalManager$toIncrementalTaskClosure$1.invoke(IncrementalManager.kt:25)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:340)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:338)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:368)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:354)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:367)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:354)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 8 column 3 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:786)
	... 19 more
```

**Comment by cbeust** [comment]
Can you paste the content of `.kobalt/build-info.json`? I suspect some bad JSON in there.

**Comment by pabl0rg** [comment]
That was it.  Invalid JSON according to sublime.

```
{
  "tasks": [
    {
      "taskName": "startrek:compile",
      "inputChecksum": "5529b160c5b09718b95a91e50de9e8d7"
    }
  ]
}um": "baabf5db7c4ea1347fa97eee9f779a5e"
    },
    {
      "taskName": "backend-java:compile",
      "inputChecksum": "e75cc0276132e18e18c237c0ff0cfb70",
      "outputChecksum": "022d206a9b6daedfd69e6665d9268965"
    },
    {
      "taskName": "kotlin part:compile",
      "inputChecksum": "d329cac14cfec89f5d2fda229d733adb",
      "outputChecksum": "1ea9d772f0cfc1363e25143a0d8f963d"
    },
    {
      "taskName": "backend-v1:compile",
      "inputChecksum": "3aa6049914ee4357f1dcc4d727fd216d",
      "outputChecksum": "9c301055dafd378fd467979410ec7278"
    },
    {
      "taskName": "backend-kotlin:compile",
      "inputChecksum": "b6f21910204d6d7616ff52c3c37872fc",
      "outputChecksum": "d11b55f5adf5b47c75129793484317c4"
    },
    {
      "taskName": "backend-java:compileTest",
      "inputChecksum": "6e34b4c3f94ce9acfb114954195e2ff3",
      "outputChecksum": "3e602b67c34a946acf5872b26342f5b8"
    },
    {
      "taskName": "backend-kotlin:compileTest",
      "inputChecksum": "386ffcaccc69af23ab393a59b23548d1",
      "outputChecksum": "db21fa84d84d1fc9d4eef5153160a32b"
    },
    {
      "taskName": "startrek:compile",
      "inputChecksum": "5529b160c5b09718b95a91e50de9e8d7",
      "outputChecksum": "2ca548b4ebcd0f61c82494d5b1ae132e"
    }
  ]
}
```

**Comment by cbeust** [comment]
So very weird, the trailing "um" at the top is probably a mangled
"outputChecksum". Wonder how that corruption occurred...


-- 
Cédric

**Comment by pabl0rg** [comment]
I'm not sure how it happened, but deleting the json fixed it.  Maybe ./kobaltw clean could also delete that json?

**Comment by cbeust** [comment]
I'd rather not, this would just paper over that bug and the philosophy of
`clean` is to delete build artifacts, not internal Kobalt structures. Let's
keep things as they are and see if the bug happens again.

The only time when `.kobalt` gets deleted is when Kobalt detects a version
upgrade (and it's necessary because the jar files in this directory might
contain code that is incompatible with the new version).


-- 
Cédric

**Comment by pabl0rg** [comment]
Would it make sense to save that .json file in the build path?  It seems like an attribute of what is built and not so much of kobalt itself.

**Comment by cbeust** [comment]
Haven't seen this in a while, closing for now.
