### ISSUE TITLE
UnkownHostException

### ISSUE THREAD

**Issue by PaulWoitaschek** [cbeust/kobalt#117]
Exception when building [MAP](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/tree/feature/kobalt/audiobook/src)

On second run this error is not shown. Happened just after updating to 0.500

```stacktrace
***** WARNING Error: java.util.concurrent.ExecutionException: java.net.UnknownHostException: repo1.maven.org
***** WARNING Error: java.util.concurrent.ExecutionException: java.net.UnknownHostException: repo1.maven.org
  Downloaded https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.0-rc-1036/kotlin-compiler-embeddable-1.0.0-rc-1036.pom
  Downloaded https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.0-rc-1036/kotlin-compiler-embeddable-1.0.0-rc-1036.jar
***** WARNING Error: java.util.concurrent.ExecutionException: java.net.UnknownHostException: repo1.maven.org
***** WARNING Error: java.util.concurrent.ExecutionException: java.net.ConnectException: Operation timed out
  Downloaded https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.0.0-rc-1036/kotlin-stdlib-1.0.0-rc-1036.pom
Exception in thread "main" *****
***** ERROR java.net.UnknownHostException: akamai.bintray.com
*****
java.util.concurrent.ExecutionException: java.net.UnknownHostException: akamai.bintray.com
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.getKotlinCompilerJar(KotlinPlugin.kt:87)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.entriesFor(KotlinPlugin.kt:95)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.entriesFor(KotlinPlugin.kt:19)
	at com.beust.kobalt.maven.DependencyManager.runClasspathContributors(DependencyManager.kt:37)
	at com.beust.kobalt.maven.DependencyManager.calculateDependencies(DependencyManager.kt:27)
	at com.beust.kobalt.maven.DependencyManager.calculateDependencies$default(DependencyManager.kt:21)
	at com.beust.kobalt.internal.JvmCompiler.doCompile(JvmCompiler.kt:27)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler.compile(KotlinCompiler.kt:133)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile(KotlinCompiler.kt:155)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile$default(KotlinCompiler.kt:154)
	at com.beust.kobalt.app.BuildFileCompiler.maybeCompileBuildFile(BuildFileCompiler.kt:110)
	at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:86)
	at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:57)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:145)
	at com.beust.kobalt.Main.access$runWithArgs(Main.kt:49)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:87)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:49)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkSeconds(Benchmarks.kt:9)
	at com.beust.kobalt.Main.run(Main.kt:85)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:46)
	at com.beust.kobalt.MainKt.main(Main.kt:28)
Caused by: java.net.UnknownHostException: akamai.bintray.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2661)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2583)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1769)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.beust.kobalt.maven.Kurl$inputStream$2.invoke(Kurl.kt:59)
	at com.beust.kobalt.maven.Kurl$inputStream$2.invoke(Kurl.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at com.beust.kobalt.maven.Kurl.getInputStream(Kurl.kt:142)
	at com.beust.kobalt.maven.Kurl.toOutputStream(Kurl.kt:94)
	at com.beust.kobalt.maven.Kurl.toFile(Kurl.kt:97)
	at com.beust.kobalt.maven.Kurl.toFile$default(Kurl.kt:96)
	at com.beust.kobalt.maven.ArtifactFetcher.call(ArtifactFetcher.kt:66)
	at com.beust.kobalt.maven.ArtifactFetcher.call(ArtifactFetcher.kt:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cbeust** [comment]
Are you behind a proxy? The host names in your trace are downright bizarre, as if they had all been rewritten...

**Comment by PaulWoitaschek** [comment]
No proxy. And only failed on first time.

**Comment by cbeust** [comment]
Weird. I just cloned your project from scratch and I didn't see any issues downloading.

**Comment by PaulWoitaschek** [comment]
Maybe it was just a temporary upgrading bug?
