### ISSUE TITLE
Can't build new project with Retrofit2

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#131]
(from Slack)

I can't build a new project with Retrofit2:

[Archive.zip](https://github.com/cbeust/kobalt/files/131815/Archive.zip)

```
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.603

          ╔═════════════════════╗
          ║ Building PokeKotlin ║
          ╚═════════════════════╝
───── PokeKotlin:compile
WARN: java.util.zip.ZipException: error in opening zip file: /Users/sargunvohra/.kobalt/repository/com/squareup/okio/okio/2.0.0-SNAPSHOT/maven-metadata.xml
java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at com.intellij.util.io.FileAccessorCache$1.createValue(FileAccessorCache.java:37)
	at com.intellij.util.io.FileAccessorCache$1.createValue(FileAccessorCache.java:30)
	at com.intellij.util.containers.SLRUCache.get(SLRUCache.java:46)
	at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:62)
	at com.intellij.openapi.vfs.impl.ZipHandler.getZipFileHandle(ZipHandler.java:106)
	at com.intellij.openapi.vfs.impl.ZipHandler.createEntriesMap(ZipHandler.java:85)
	at com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:130)
	at com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:40)
	at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:37)
	at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:33)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
	at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:50)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:228)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:207)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.fillClasspath(KotlinCoreEnvironment.kt:180)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:129)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:98)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:281)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:212)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:182)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:49)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:174)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:135)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.doMainNoExit(CLICompiler.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.invokeCompiler(KotlinCompiler.kt:87)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.compile(KotlinCompiler.kt:61)
	at com.beust.kobalt.internal.JvmCompiler.doCompile(JvmCompiler.kt:47)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler.compile(KotlinCompiler.kt:135)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile(KotlinCompiler.kt:157)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.compilePrivate(KotlinPlugin.kt:92)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.access$compilePrivate(KotlinPlugin.kt:20)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin$compiler$1.compile(KotlinPlugin.kt:123)
	at com.beust.kobalt.internal.JvmCompilerPlugin.doTaskCompile(JvmCompilerPlugin.kt:185)
	at com.beust.kobalt.internal.JvmCompilerPlugin.doTaskCompile(JvmCompilerPlugin.kt:155)
	at com.beust.kobalt.internal.JvmCompilerPlugin.access$doTaskCompile(JvmCompilerPlugin.kt:28)
	at com.beust.kobalt.internal.JvmCompilerPlugin$taskCompile$2.invoke(JvmCompilerPlugin.kt:151)
	at com.beust.kobalt.internal.JvmCompilerPlugin$taskCompile$2.invoke(JvmCompilerPlugin.kt:28)
	at com.beust.kobalt.internal.IncrementalManager$toIncrementalTaskClosure$1.invoke(IncrementalManager.kt:110)
	at com.beust.kobalt.internal.IncrementalManager$toIncrementalTaskClosure$1.invoke(IncrementalManager.kt:27)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:340)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:338)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:368)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:354)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:367)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:354)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:120)
	at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:53)
	at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:45)
	at com.intellij.util.io.FileAccessorCache$1.createValue(FileAccessorCache.java:35)
	... 56 more
WARN: java.util.zip.ZipException: error in opening zip file: /Users/sargunvohra/.kobalt/repository/com/squareup/okhttp3/okhttp/3.2.0-SNAPSHOT/maven-metadata.xml
java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
	at com.intellij.util.io.FileAccessorCache$1.createValue(FileAccessorCache.java:37)
	at com.intellij.util.io.FileAccessorCache$1.createValue(FileAccessorCache.java:30)
	at com.intellij.util.containers.SLRUCache.get(SLRUCache.java:46)
	at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:62)
	at com.intellij.openapi.vfs.impl.ZipHandler.getZipFileHandle(ZipHandler.java:106)
	at com.intellij.openapi.vfs.impl.ZipHandler.createEntriesMap(ZipHandler.java:85)
	at com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:130)
	at com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:40)
	at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:37)
	at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem$1.create(CoreJarFileSystem.java:33)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
	at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:50)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:228)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:207)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.fillClasspath(KotlinCoreEnvironment.kt:180)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:129)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:98)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:281)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:212)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:182)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:49)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:174)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:135)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.doMainNoExit(CLICompiler.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.invokeCompiler(KotlinCompiler.kt:87)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.compile(KotlinCompiler.kt:61)
	at com.beust.kobalt.internal.JvmCompiler.doCompile(JvmCompiler.kt:47)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler.compile(KotlinCompiler.kt:135)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile(KotlinCompiler.kt:157)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.compilePrivate(KotlinPlugin.kt:92)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.access$compilePrivate(KotlinPlugin.kt:20)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin$compiler$1.compile(KotlinPlugin.kt:123)
	at com.beust.kobalt.internal.JvmCompilerPlugin.doTaskCompile(JvmCompilerPlugin.kt:185)
	at com.beust.kobalt.internal.JvmCompilerPlugin.doTaskCompile(JvmCompilerPlugin.kt:155)
	at com.beust.kobalt.internal.JvmCompilerPlugin.access$doTaskCompile(JvmCompilerPlugin.kt:28)
	at com.beust.kobalt.internal.JvmCompilerPlugin$taskCompile$2.invoke(JvmCompilerPlugin.kt:151)
	at com.beust.kobalt.internal.JvmCompilerPlugin$taskCompile$2.invoke(JvmCompilerPlugin.kt:28)
	at com.beust.kobalt.internal.IncrementalManager$toIncrementalTaskClosure$1.invoke(IncrementalManager.kt:110)
	at com.beust.kobalt.internal.IncrementalManager$toIncrementalTaskClosure$1.invoke(IncrementalManager.kt:27)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:340)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:338)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:368)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:354)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:367)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:354)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:120)
	at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:53)
	at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:45)
	at com.intellij.util.io.FileAccessorCache$1.createValue(FileAccessorCache.java:35)
	... 56 more
src/main/kotlin/me/sargunvohra/lib/pokekotlin/Main.kt:9:39: error: overload resolution ambiguity: 
public open fun baseUrl(baseUrl: [ERROR : Unresolved java classifier: HttpUrl]!): retrofit2.Retrofit.Builder! defined in retrofit2.Retrofit.Builder
public open fun baseUrl(baseUrl: kotlin.String!): retrofit2.Retrofit.Builder! defined in retrofit2.Retrofit.Builder
    val retrofit = Retrofit.Builder().baseUrl("http://pokeapi.co/api/v2").build()
                                      ^
BUILD FAILED: 1
```

**Comment by cbeust** [comment]
This is happening because retrofit depends on the okhttp3 SNAPSHOT, so you need to explicitly add the maven snapshot repo to your build file:

```
val repos = repos("https://oss.sonatype.org/content/repositories/snapshots")
```

However, even with this, Kobalt is having a hard time resolving the snapshot:

```
 ./kobaltw --resolve com.squareup.okhttp3:okhttp:3.2.0-SNAPSHOT --log 2
```

so I'm leaving this issue open.

**Comment by sargunster** [comment]
Thanks, I was able to compile by manually specifying non-snapshot versions of OkHttp, Okio, and Moshi. Of course, this will break if Retrofit requires a feature from a snapshot version.

**Comment by cbeust** [comment]
Great. I'll leave this issue open since Kobalt should be able to handle
this kind of indirect SNAPSHOT dependency so I'll fix it.

-- 
Cédric

**Comment by cbeust** [comment]
I can resolve the snapshot now:

```
$ ./kobaltw --resolve com.squareup.okhttp3:okhttp:3.2.0-SNAPSHOT 
╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                    com.squareup.okhttp3:okhttp:3.2.0-SNAPSHOT                                          ║
║           https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okhttp3/okhttp/3.2.0-SNAPSHOT/okhttp-3.2.0-SNAPSHOT.jar ║
║                       /Users/beust/.kobalt/repository/com/squareup/okhttp3/okhttp/3.2.0-SNAPSHOT/okhttp-3.2.0-SNAPSHOT.jar             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
╙ com.squareup.okio:okio:1.6.0
```

**Comment by sargunster** [comment]
Yep, this works now. Thanks!
