### ISSUE TITLE
Weird Kobalt exception on opening non-kobalt project

### ISSUE THREAD

**Issue by AlexCzar** [cbeust/kobalt#154]
IntelliJ version: **2016.1 Ultimate**
Kobalt plugin version: **1.46**
Steps to reproduce: open gradle project, you'll see the following crash in event log:
```
Assertion failed: Attempt to start ProgressIndicator which is already running
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:156)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.start(AbstractProgressIndicatorBase.java:60)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.start(AbstractProgressIndicatorExBase.java:98)
	at com.intellij.openapi.progress.util.StatusBarProgress.start(StatusBarProgress.java:42)
	at com.beust.kobalt.intellij.DistributionDownloader.install(DistributionDownloader.kt:62)
	at com.beust.kobalt.intellij.KobaltApplicationComponent$initComponent$1$1.run(KobaltApplicationComponent.kt:82)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cbeust** [comment]
Mmmh looks like my fix didn't work. That's weird, I moved the init code to the `ApplicationComponent`, which should only be invoked once. Will investigate.

**Comment by cbeust** [comment]
Fixed by https://github.com/cbeust/kobalt-intellij-plugin/commit/f19388e7e317452e3824b4c803d8277b98915f72
