### ISSUE TITLE
pom.xml not imported correctly

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#158]
_Edited (Cédric)_

The problem is that the Eclipse dependencies were not imported from `pom.xml`

_End edited_

`./kobaltw --resolve org.mapdb:mapdb:3.0.0-M3`

It should have some dependencies, but they're missing. This causes class not found errors when I run a project that depends on this library.

Relevant pom file: http://central.maven.org/maven2/org/mapdb/mapdb/3.0.0-M3/mapdb-3.0.0-M3.pom

My repo affected by this: https://github.com/pokesource/ditto

**Comment by cbeust** [comment]
Your project seems to build for me:

```
───── ditto:assemble
  Created ./kobaltBuild/libs/ditto-0.1.0.jar
```

As does the `resolve`:

```
$ ./kobaltw --resolve org.mapdb:mapdb:3.0.0-M3
              __ __           __              __   __
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  0.689

╔═══════════════════════════════════════════════════════════════════════════════════════╗
║                                    org.mapdb:mapdb:3.0.0-M3                           ║
║            http://repo1.maven.org/maven2/org/mapdb/mapdb/3.0.0-M3/mapdb-3.0.0-M3.jar  ║
║           /Users/beust/.kobalt/repository/org/mapdb/mapdb/3.0.0-M3/mapdb-3.0.0-M3.jar ║
╚═══════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by sargunster** [comment]
It builds but doesn't run because the MapDB library has some dependencies that don't get pulled in. You can see when you `resolve` that no dependencies are shown, but in the pom.xml I linked above there should be a few dependencies (Guava and others). When I add those manually in my `Build.kt`, it works.

**Comment by cbeust** [comment]
Ah indeed, `./kobaltw run` fails:

```
───── ditto:run
ERROR
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/collections/impl/list/mutable/primitive/LongArrayList
	at org.mapdb.StoreDirect.<init>(StoreDirect.kt:94)
	at org.mapdb.StoreDirect$Companion.make(StoreDirect.kt:36)
	at org.mapdb.StoreDirect$Companion.make$default(StoreDirect.kt:35)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:96)
	at com.github.pokesource.ditto.data.Cache.<init>(Cache.kt:15)
	at com.github.pokesource.ditto.MainKt.startServices(Main.kt:87)
	at com.github.pokesource.ditto.MainKt.main(Main.kt:17)
Caused by: java.lang.ClassNotFoundException: org.eclipse.collections.impl.list.mutable.primitive.LongArrayList
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by aneophyte** [comment]
It seems like this and https://github.com/cbeust/kobalt/issues/157 are related issues.
