### ISSUE TITLE
Allow override kotlin version in kotlin projects

### ISSUE THREAD

**Issue by fboldog** [cbeust/kobalt#166]
Adding this into Build.kt
```kotlin
    dependencies {
        compile("org.jetbrains.kotlin:kotlin-stdlib:1.0.2-eap-15")
   }
```
will cause this error:
```
*****
***** ERROR
       UNEXPECTED TOP-LEVEL EXCEPTION:
       com.android.dex.DexException: Multiple dex files define Lkotlin/ExceptionsKt__ExceptionsKt;
       	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
       	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
       	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
       	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
       	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
       	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
       	at com.android.dx.command.dexer.Main.run(Main.java:277)
       	at com.android.dx.command.dexer.Main.main(Main.java:245)
       	at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by cbeust** [comment]
You can now add the following to `~/.config/kobalt/settings.xml`:

```
<kobalt-settings>
	<kobalt-compiler-version>1.0.2-eap-15</kobalt-compiler-version>
	<kobalt-compiler-repo>https://dl.bintray.com/kotlin/kotlin-eap</kobalt-compiler-repo>
</kobalt-settings>
```

**Comment by pabl0rg** [comment]
if someone is looking for how to do this with kobalt .905 the xml tags changed to camelCase

to use the latest kotlin compiler: 
```
<kobaltSettings>
    <kobaltCompilerVersion>1.0.5</kobaltCompilerVersion>
</kobaltSettings>
```

**Comment by cbeust** [comment]
Yup, that;s correct, thanks @pabl0rg.
