### ISSUE TITLE
kobaltw Couldn't find kobalt.properties

### ISSUE THREAD

**Issue by kmruiz** [cbeust/kobalt#179]
After installing a fresh Kobalt 0.752 in a new machine, when running any kobalt command it shows the following error and stack trace:

```
Exception in thread "main" java.lang.IllegalArgumentException: Couldn't find kobalt.properties
        at com.beust.kobalt.wrapper.Main.maybeCreateProperties(Main.java:106)
        at com.beust.kobalt.wrapper.Main.getVersion(Main.java:40)
        at com.beust.kobalt.wrapper.Main.installAndLaunchMain(Main.java:45)
        at com.beust.kobalt.wrapper.Main.main(Main.java:15)
```

This doesn't happen on version 0.751.

**Comment by cbeust** [comment]
Yes I see it to. The task that copies this file is no longer being invoked, looking into it.

**Comment by cbeust** [comment]
Should be fixed in the latest, can you try?

**Comment by kmruiz** [comment]
:+1: works as expected.

Thanks!!
