### ISSUE TITLE
Error synchronizing with Intellij IDEA

### ISSUE THREAD

**Issue by kmruiz** [cbeust/kobalt#180]
Using Kobalt 0.747 when synchronizing with IDEA (2016.1) it fails with the current error and stacktrace:

```
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at com.beust.kobalt.intellij.DependenciesProcessor$sendGetDependencies$1.run(DependenciesProcessor.kt:110)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
	at com.beust.kobalt.intellij.DependenciesProcessor.sendGetDependencies(DependenciesProcessor.kt:94)
	at com.beust.kobalt.intellij.DependenciesProcessor.access$sendGetDependencies(DependenciesProcessor.kt:23)
	at com.beust.kobalt.intellij.DependenciesProcessor$run$$inlined$with$lambda$1.invoke(DependenciesProcessor.kt:39)
	at com.beust.kobalt.intellij.DependenciesProcessor$run$$inlined$with$lambda$1.invoke(DependenciesProcessor.kt:23)
	at com.beust.kobalt.intellij.ServerUtil$Companion$toBackgroundTask$1.run(ServerUtil.kt:21)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1373)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 21 more
``` 
Plugin version: 1.57

**Comment by kmruiz** [comment]
It also happens with 0.755
