### ISSUE TITLE
kobaltw crashes if file .kobalt/wrapperVersion.txt does not exists

### ISSUE THREAD

**Issue by kmruiz** [cbeust/kobalt#181]
This happens on travis, where this file never exists and should be created.

```
Exception in thread "main" java.io.FileNotFoundException: .kobalt/wrapperVersion.txt (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at com.beust.kobalt.wrapper.Main.installWrapperFiles(Main.java:254)
        at com.beust.kobalt.wrapper.Main.installDistribution(Main.java:219)
        at com.beust.kobalt.wrapper.Main.installAndLaunchMain(Main.java:77)
        at com.beust.kobalt.wrapper.Main.main(Main.java:15)
```

Verbose:

```
[21:18:32] kevin kobalt-jacoco $ ./kobaltw test --log 2
[Wrapper] Wrapper version: 0.754
[Wrapper]   Couldn't find $VERSION_TEXT, overwriting the installed wrapper
[Wrapper]   Generating kobaltw with shebang.
[Wrapper]   Writing kobalt/wrapper/kobalt-wrapper.jar
[Wrapper]   Writing .kobalt/wrapperVersion.txt
Exception in thread "main" java.io.FileNotFoundException: .kobalt/wrapperVersion.txt (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at com.beust.kobalt.wrapper.Main.installWrapperFiles(Main.java:254)
        at com.beust.kobalt.wrapper.Main.installDistribution(Main.java:219)
        at com.beust.kobalt.wrapper.Main.installAndLaunchMain(Main.java:77)
        at com.beust.kobalt.wrapper.Main.main(Main.java:15)
```

**Comment by kmruiz** [comment]
I'm looking at the code and looks that the problem is here:

```kotlin
VERSION_TXT.getParentFile().mkdirs();
```

At line 254 of class Main.kt

However, I don't know why mkdirs could be failing.

**Comment by kmruiz** [comment]
Travis build that crashes:

https://travis-ci.org/kmruiz/kobalt-jacoco/builds/127067640
