### ISSUE TITLE
Kobalt 0.768 NPE

### ISSUE THREAD

**Issue by kmruiz** [cbeust/kobalt#194]
```
[Wrapper] Warning: could not create the directory /home/kevin/Projects/oss/kobalt/.kobalt, can't write .kobalt/wrapperVersion.txt
              __ __           __              __   __ 
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_  
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  0.768

Detected new installation, wiping /home/kevin/Projects/oss/kobalt/.kobalt/build
Exception in thread "main" java.lang.NullPointerException
        at com.beust.kobalt.internal.build.BuildFile.<init>(BuildFile.kt:30)
        at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:94)
        at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:57)
        at com.beust.kobalt.Main.initForBuildFile(Main.kt:230)
        at com.beust.kobalt.Main.runWithArgs(Main.kt:180)
        at com.beust.kobalt.Main.access$runWithArgs(Main.kt:55)
        at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:116)
        at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:55)
        at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
        at com.beust.kobalt.misc.BenchmarksKt.benchmarkSeconds(Benchmarks.kt:9)
        at com.beust.kobalt.Main.run(Main.kt:114)
        at com.beust.kobalt.MainKt.mainNoExit(Main.kt:47)
        at com.beust.kobalt.MainKt.main(Main.kt:29)
```

Just downloaded the code and any call to kobalt throws that exception. Version 0.760 works fine. Tried to debug it but didn't find any reason :disappointed: .

**Comment by kmruiz** [comment]
The program does not stop and needs to be killed manually using `kill`

**Comment by cbeust** [comment]
This expression in `BuildFile.kt` is crashing:

**Comment by cbeust** [comment]
This expression in `BuildFile.kt` is crashing:

```
    val absoluteDir = path.parent.parent.parent.toFile()
```

Post the value `path`, which should point to `kobalt/src/Build.kt` but apparently is not, otherwise we should be able to get two levels up.

You can do this either from IDEA or if the crash only happens from the shell, build it and invoke the new jar directly:

```
java -jar kobaltBuild/libs/kobalt-0.768.jar
```

**Comment by cbeust** [comment]
When it crashes, the executors are not shut down properly, I can look into
that but right now, I can't reproduce your crash so you're going to have to
either fix it yourself or give me more information about it :-)

-- 
Cédric

**Comment by kmruiz** [comment]
BuildFile could be (and possibly there are few times) in a temporary folder, that's why it crashes :-).  I'll do a PR with the code that solves this issue.
