### ISSUE TITLE
NPE while trying to generate "kobaltPlugin" template

### ISSUE THREAD

**Issue by dmitry-zhuravlev** [cbeust/kobalt#200]
java -Dfile.encoding=windows-1251 -classpath C:\Users\user\.kobalt\wrapper\dist\kobalt-0.777\kobalt\wrapper\kobalt-0.777.jar
 com.beust.kobalt.wrapper.Main --init kobaltPlugin
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.777

Exception in thread "main" java.lang.NullPointerException
        at com.beust.kobalt.api.JarTemplate.generateTemplate(JarTemplate.kt:37)
        at com.beust.kobalt.app.ProjectGenerator.run(ProjectGenerator.kt:28)
        at com.beust.kobalt.Main.runWithArgs(Main.kt:154)
        at com.beust.kobalt.Main.access$runWithArgs(Main.kt:55)
        at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:117)
        at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:55)
        at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
        at com.beust.kobalt.misc.BenchmarksKt.benchmarkSeconds(Benchmarks.kt:9)
        at com.beust.kobalt.Main.run(Main.kt:115)
        at com.beust.kobalt.MainKt.mainNoExit(Main.kt:47)
        at com.beust.kobalt.MainKt.main(Main.kt:29)
@cbeust

**Comment by cbeust** [comment]
Fixed in 0.778.
