### ISSUE TITLE
productFlavor is broken?

### ISSUE THREAD

**Issue by maxd** [cbeust/kobalt#202]
Look at demo [project](https://github.com/maxd/kobalt-productFlavor-experiment).

In this project "run" task works fine:

```
➜  kobalt-productFlavor-experiment git:(master) ./kobaltw run
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.780

          ╔══════════════════════════════════════════╗
          ║ Building kobalt-productFlavor-experiment ║
          ╚══════════════════════════════════════════╝
───── kobalt-productFlavor-experiment:compile
───── kobalt-productFlavor-experiment:assemble
───── kobalt-productFlavor-experiment:install
Installing from ./kobaltBuild/libs to libs
───── kobalt-productFlavor-experiment:run


Hello Kotlin world from Kobalt


BUILD SUCCESSFUL (0 seconds)
```

but "runFeature1" task with flavor throw the error:

```
              __ __           __              __   __
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  0.780

          ╔══════════════════════════════════════════╗
          ║ Building kobalt-productFlavor-experiment ║
          ╚══════════════════════════════════════════╝
───── kobalt-productFlavor-experiment:runFeature1
───── kobalt-productFlavor-experiment:runFeature1
*****
***** ERROR Error: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
*****
BUILD FAILED: 1
```

So, is this problem in configuration of my demo project or productFlavor is broken?

Stacktrace:

```
*****
***** ERROR Error: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
*****
java.util.concurrent.ExecutionException: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.beust.kobalt.internal.DynamicGraphExecutor.run2(DynamicGraph.kt:153)
	at com.beust.kobalt.internal.DynamicGraphExecutor.run(DynamicGraph.kt:134)
	at com.beust.kobalt.internal.TaskManager.runTargets(TaskManager.kt:135)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:208)
	at com.beust.kobalt.Main.access$runWithArgs(Main.kt:55)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:117)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:55)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkSeconds(Benchmarks.kt:9)
	at com.beust.kobalt.Main.run(Main.kt:115)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:47)
	at com.beust.kobalt.MainKt.main(Main.kt:29)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
	at com.beust.kobalt.plugin.application.ApplicationPlugin.runJarFile(ApplicationPlugin.kt:98)
	at com.beust.kobalt.plugin.application.ApplicationPlugin.run(ApplicationPlugin.kt:89)
	at com.beust.kobalt.plugin.application.ApplicationPlugin.taskRun(ApplicationPlugin.kt:60)
	at com.beust.kobalt.plugin.application.ApplicationPlugin$apply$1.invoke(ApplicationPlugin.kt:52)
	at com.beust.kobalt.plugin.application.ApplicationPlugin$apply$1.invoke(ApplicationPlugin.kt:38)
	at com.beust.kobalt.api.TaskContributor$addVariantTasks$$inlined$forEach$lambda$1.invoke(TaskContributor.kt:41)
	at com.beust.kobalt.api.TaskContributor$addVariantTasks$$inlined$forEach$lambda$1.invoke(TaskContributor.kt:13)
	at com.beust.kobalt.api.DynamicTask.call(ITaskContributor.kt:25)
	at com.beust.kobalt.api.DynamicTask.call(ITaskContributor.kt:14)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:563)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:549)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:562)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cbeust** [comment]
Will take a look.

**Comment by cbeust** [comment]
This should be fixed now, can you try again?

**Comment by maxd** [comment]
Checked after close #205. kobalt throw the same exception.

**Comment by cbeust** [comment]
This should be fixed with the latest:

**Comment by cbeust** [comment]
This should be fixed in the latest:

```
$ k runFeature1
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.788

          ╔══════════════════════════════════════════╗
          ║ Building kobalt-productFlavor-experiment ║
          ╚══════════════════════════════════════════╝
───── kobalt-productFlavor-experiment:runFeature1
Hello Kotlin world from Kobalt
```

**Comment by maxd** [comment]
I think `runFeature1` should call `assembleFeature1` before run application. Right?

**Comment by cbeust** [comment]
Indeed, there was a bug which should now be fixed.

**Comment by maxd** [comment]
Now variants work fine. 👍  Thank you.
