### ISSUE TITLE
Exception when one module depends on the jar from another module

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#210]
I'm trying to write an annotation processor for my project. I've created a separate module "CodeGen" and set my main module "PokeKotlin" to depend on it. When I add the file dependency, I get an exception when running any Kobalt task. 

The code is in the "apt" branch of my repo: https://github.com/pokesource/pokekotlin/tree/apt

```
file("CodeGen/kobaltBuild/libs/CodeGen-${Versions.pokekotlin}.jar").let {
    apt(it)
    compile(it)
}
```
```
Exception in thread "main" java.util.NoSuchElementException: No element matching predicate was found.
        at com.beust.kobalt.maven.DependencyManager.create(DependencyManager.kt:225)
        at com.beust.kobalt.maven.DependencyManager$Companion.create(DependencyManager.kt:22)
        at com.beust.kobalt.api.Dependencies.addToDependencies(Project.kt:149)
        at com.beust.kobalt.api.Dependencies.compile(Project.kt:155)
        at Kobalt8591121999509635894Kt$pokekotlin$1$3.invoke(kobalt8591121999509635894.kt:64)
        at Kobalt8591121999509635894Kt$pokekotlin$1$3.invoke(kobalt8591121999509635894.kt)
        at com.beust.kobalt.api.DependencyHolder.dependencies(DependencyHolder.kt:37)
        at com.beust.kobalt.api.Project.dependencies(Project.kt)
        at Kobalt8591121999509635894Kt$pokekotlin$1.invoke(kobalt8591121999509635894.kt:55)
        at Kobalt8591121999509635894Kt$pokekotlin$1.invoke(kobalt8591121999509635894.kt)
        at com.beust.kobalt.DirectivesKt.project(Directives.kt:11)
        at Kobalt8591121999509635894Kt.<clinit>(kobalt8591121999509635894.kt:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.beust.kobalt.app.BuildScriptUtil.runBuildScriptJarFile(BuildScriptUtil.kt:83)
        at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:98)
        at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:57)
        at com.beust.kobalt.Main.initForBuildFile(Main.kt:231)
        at com.beust.kobalt.Main.runWithArgs(Main.kt:181)
        at com.beust.kobalt.Main.access$runWithArgs(Main.kt:55)
        at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:117)
        at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:55)
        at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
        at com.beust.kobalt.misc.BenchmarksKt.benchmarkSeconds(Benchmarks.kt:9)
        at com.beust.kobalt.Main.run(Main.kt:115)
        at com.beust.kobalt.MainKt.mainNoExit(Main.kt:47)
        at com.beust.kobalt.MainKt.main(Main.kt:29)
```

**Comment by DevCharly** [comment]
I've seen exactly the same exception too.
It occurs if the file in `file()` does not exist on the filesystem.

In my case I'm doing:
```
object Libraries {
	val lib1 = file("lib1.jar")
}

var proj = project {
	dependencies {
		compile( Libraries.lib1 )
	}
}
```
It works if lib1.jar exists, but throws the above exception if lib1.jar does not exist

**Comment by sargunster** [comment]
It's impossible for the file to exist because the exception happens when I try to assemble it.
