### ISSUE TITLE
Package not created on bintray

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt#250]
Tried to upload a brand new project to bintray (without creating the package there):

```
───── kobalt-groovy:assemble
Directory docs/javadoc/ doesn't exist, not including it in the jar
  Created ./kobaltBuild/libs/kobalt-groovy-0.1.pom
    INC - Incremental task kobalt-groovy:assemble done running, saving checksums
Task succeeded: {TaskResult value:kobalt-groovy:assemble, success:true}
  Removing kobalt-groovy:assemble
───── kobalt-groovy:generatePom
  Created ./kobaltBuild/libs/kobalt-groovy-0.1.pom
Task succeeded: {TaskResult value:kobalt-groovy:generatePom, success:true}
  Removing kobalt-groovy:generatePom
───── kobalt-groovy:uploadBintray
***** WARNING Package does not exist on bintray.  Creating now.
*****
***** ERROR Error: com.google.gson.JsonObject cannot be cast to java.io.File
*****
java.lang.ClassCastException: com.google.gson.JsonObject cannot be cast to java.io.File
	at com.beust.kobalt.plugin.publish.RequestBodyConverter.convert(BintrayApi.kt:235)
	at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:270)
	at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:108)
	at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:162)
	at com.beust.kobalt.plugin.publish.BintrayApi.validatePackage(BintrayApi.kt:105)
	at com.beust.kobalt.plugin.publish.BintrayApi.uploadMaven(BintrayApi.kt:127)
	at com.beust.kobalt.plugin.publish.PublishPlugin.uploadBintray(PublishPlugin.kt:80)
	at com.beust.kobalt.plugin.publish.PublishPlugin.taskUploadBintray(PublishPlugin.kt:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.beust.kobalt.internal.TaskManager$toTaskAnnotation$1.invoke(TaskManager.kt:401)
	at com.beust.kobalt.internal.TaskManager$toTaskAnnotation$1.invoke(TaskManager.kt:19)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:475)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:473)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:514)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:500)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:513)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:500)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Marking project kobalt-groovy as failed
```

**Comment by cbeust** [comment]
ping @evanchooly
