### ISSUE TITLE
regression when running the Homebrew test: java.lang.NoSuchMethodError: org.apache.http.client.utils.URIUtils.extractHost

### ISSUE THREAD

**Issue by ilovezfs** [cbeust/kobalt#287]
Homebrew runs the following test:
```
  test do
    ENV.java_cache

    (testpath/"src/main/kotlin/com/A.kt").write <<-EOS.undent
      package com
      class A
      EOS

    (testpath/"kobalt/src/Build.kt").write <<-EOS.undent
      import com.beust.kobalt.*
      import com.beust.kobalt.api.*
      import com.beust.kobalt.plugin.packaging.*

      val p = project {
        name = "test"
        version = "1.0"
        assemble {
          jar {}
        }
      }
    EOS

    system "#{bin}/kobaltw", "assemble"
    output = "kobaltBuild/libs/test-1.0.jar"
    assert File.exist?(output), "Couldn't find #{output}"
  end
```

A regression showed up when trying to upgrade the formula from 0.853 to 0.859.
```
bash-3.2$ /usr/local/Cellar/kobalt/0.859/bin/kobaltw --log 3 assemble
Picked up _JAVA_OPTIONS: -Duser.home=/Users/joe/Library/Caches/Homebrew/java_cache
[Wrapper] Wrapper version: 0.859
[Wrapper]   Trying to install the same version 0.859 == 0.859, not overwriting the installed wrapper
[Wrapper] Launching [java, -Dfile.encoding=US-ASCII, -jar, /Users/joe/Library/Caches/Homebrew/java_cache/.kobalt/wrapper/dist/kobalt-0.859/kobalt/wrapper/kobalt-0.859.jar, --log, 3, assemble]
Picked up _JAVA_OPTIONS: -Duser.home=/Users/joe/Library/Caches/Homebrew/java_cache
Couldn't find /Users/joe/Library/Caches/Homebrew/java_cache/.config/kobalt/settings.xml, using default settings
URL for core kobalt-plugin.xml: jar:file:/Users/joe/Library/Caches/Homebrew/java_cache/.kobalt/wrapper/dist/kobalt-0.859/kobalt/wrapper/kobalt-0.859.jar!/META-INF/kobalt-core-plugin.xml
Parsed plugin XML file, found: kobalt
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.859

Saved /var/folders/w6/9r0nb9011glb8fdz__srd78c0000gq/T/kobalt7409430790030076742.kt
Script jar file: /private/tmp/kobalt-test-20160720-33576-ri6fj1/.kobalt/build/preBuildScript.jar
*****
***** ERROR org.apache.http.client.utils.URIUtils.extractHost(Ljava/net/URI;)Lorg/apache/http/HttpHost;
*****
java.lang.NoSuchMethodError: org.apache.http.client.utils.URIUtils.extractHost(Ljava/net/URI;)Lorg/apache/http/HttpHost;
	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:115)
	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:93)
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:110)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:115)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at com.beust.kobalt.maven.aether.Aether.resolve(Aether.kt:169)
	at com.beust.kobalt.maven.aether.AetherDependency.getJarFile(Aether.kt:206)
	at com.beust.kobalt.internal.KotlinJarFiles.getKotlinCompilerJar(KotlinJarFiles.kt:15)
	at com.beust.kobalt.internal.KotlinJarFiles.getStdlib(KotlinJarFiles.kt:18)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.classpathEntriesFor(KotlinPlugin.kt:104)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.classpathEntriesFor(KotlinPlugin.kt:19)
	at com.beust.kobalt.maven.DependencyManager.runClasspathContributors(DependencyManager.kt:103)
	at com.beust.kobalt.maven.DependencyManager.calculateDependencies(DependencyManager.kt:93)
	at com.beust.kobalt.app.ParsedBuildFile.generateJarFile(ParsedBuildFile.kt:147)
	at com.beust.kobalt.app.ParsedBuildFile.initPluginUrls(ParsedBuildFile.kt:122)
	at com.beust.kobalt.app.ParsedBuildFile.<init>(ParsedBuildFile.kt:41)
	at com.beust.kobalt.app.BuildFileCompiler.parseBuildFile(BuildFileCompiler.kt:162)
	at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:75)
	at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:61)
	at com.beust.kobalt.app.ProjectFinder.initForBuildFile(ProjectFinder.kt:20)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:181)
	at com.beust.kobalt.Main.access$runWithArgs(Main.kt:56)
	at com.beust.kobalt.Main$run$timing$1.invoke(Main.kt:117)
	at com.beust.kobalt.Main$run$timing$1.invoke(Main.kt:56)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkSeconds(Benchmarks.kt:10)
	at com.beust.kobalt.Main.run(Main.kt:115)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:48)
	at com.beust.kobalt.MainKt.main(Main.kt:26)
BUILD FAILED: 1
```

Sequential upgrades 0.8.5.3 -> 0.8.5.4 -> ... -> 0.8.5.9 and running the test at each step seems to work, so perhaps something gets cached when doing that, but isn't there on a clean install.

The regression appears to have occurred in 0.8.5.7. 0.8.5.6 does not suffer from this problem as far as I can tell.

**Comment by cbeust** [comment]
First of all, thanks for keeping Kobalt updated in Homebrew, really
appreciate it.

Second... I have no idea what's going on there, I'll investigate.

-- 
Cédric

**Comment by ethauvin** [comment]
Steps to reproduce, run:

`kobaltw --init kotlin`

Edit `Build.kt` with:

```kotlin
dependencies {
    compile("net.objecthunter:exp4j:0.4.7")
}
```
The key is to use a library that is **not** already in the cache.

Change `Main.kt` to:
```kotlin
package com.example

import net.objecthunter.exp4j.ExpressionBuilder

fun main(args: Array<String>) {
    val calc = ExpressionBuilder("1+1").build();
    println(calc.evaluate())
 }
```
Finally:

```./kobaltw run```

**Comment by cbeust** [comment]
Starting from a specific version I haven't quite identified yet (maybe 0.853), `kobalt.jar` contains an older version of `httpclient`.

Note in the output below that `URIUtils` in 0.860 doesn't contain `extractHost()` but 0.850 does.

Now I need to find out what is pulling in this old `httpclient`.

```
$ javap -cp ~/.kobalt/wrapper/dist/kobalt-0.860/kobalt/wrapper/kobalt-0.860.jar org.apache.http.client.utils.URIUtils
Compiled from "URIUtils.java"
public class org.apache.http.client.utils.URIUtils {
  public static java.net.URI createURI(java.lang.String, java.lang.String, int, java.lang.String, java.lang.String, java.lang.String) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost, boolean) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost) throws java.net.URISyntaxException;
  public static java.net.URI resolve(java.net.URI, java.lang.String);
  public static java.net.URI resolve(java.net.URI, java.net.URI);
}
$ javap -cp ~/.kobalt/wrapper/dist/kobalt-0.850/kobalt/wrapper/kobalt-0.850.jar org.apache.http.client.utils.URIUtils
Compiled from "URIUtils.java"
public class org.apache.http.client.utils.URIUtils {
  public static java.net.URI createURI(java.lang.String, java.lang.String, int, java.lang.String, java.lang.String, java.lang.String) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost, boolean) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI, org.apache.http.HttpHost) throws java.net.URISyntaxException;
  public static java.net.URI rewriteURI(java.net.URI) throws java.net.URISyntaxException;
  public static java.net.URI resolve(java.net.URI, java.lang.String);
  public static java.net.URI resolve(java.net.URI, java.net.URI);
  public static org.apache.http.HttpHost extractHost(java.net.URI);
  public static java.net.URI resolve(java.net.URI, org.apache.http.HttpHost, java.util.List<java.net.URI>) throws java.net.URISyntaxException;
}
```

**Comment by ilovezfs** [comment]
@cbeust Thank you for the quick fix. I just shipped the new version: https://github.com/Homebrew/homebrew-core/commit/2e35cf766cdf65c54c86bbf2655b25cc44e4c431

**Comment by cbeust** [comment]
Great, and thanks again for the Homebrew updates!

**Comment by ilovezfs** [comment]
You're welcome!
