### ISSUE TITLE
Show a more friendly message if the package doesn't exist in JCenter

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt#31]
```
========== MashovApi:uploadJcenter
***** ERROR Error: java.lang.reflect.InvocationTargetException Exception: java.lang.reflect.InvocationTargetException
java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.beust.kobalt.internal.DynamicGraphExecutor.run(DynamicGraph.kt:62)
        at com.beust.kobalt.internal.TaskManager.runTargets(TaskManager.kt:137)
        at com.beust.kobalt.Main.runWithArgs(Main.kt:172)
        at com.beust.kobalt.Main.access$runWithArgs(Main.kt:44)
        at com.beust.kobalt.Main$run$1.invoke(Main.kt:74)
        at com.beust.kobalt.Main$run$1.invoke(Main.kt:44)
        at com.beust.kobalt.misc.BenchmarksKt.benchmark(Benchmarks.kt:5)
        at com.beust.kobalt.Main.run(Main.kt:71)
        at com.beust.kobalt.MainKt.mainNoExit(Main.kt:41)
        at com.beust.kobalt.MainKt.main(Main.kt:24)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.beust.kobalt.Plugins$applyPlugins$1$7$1$result$1.invoke(Plugins.kt:141)
        at com.beust.kobalt.Plugins$applyPlugins$1$7$1$result$1.invoke(Plugins.kt:31)
        at com.beust.kobalt.api.Plugin$addTask$1.call(Plugin.kt:33)
        at com.beust.kobalt.api.Plugin$addTask$1.call(Plugin.kt:31)
        at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:218)
        at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:205)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.beust.kobalt.plugin.publish.JCenterApi.packageExists(JCenterApi.kt:63)
        at com.beust.kobalt.plugin.publish.JCenterApi.uploadMaven(JCenterApi.kt:75)
        at com.beust.kobalt.plugin.publish.PublishPlugin.taskUploadJcenter(PublishPlugin.kt:76)
```

**Comment by cbeust** [comment]
@yoavst
