### ISSUE TITLE
Resolve artifacts from private server

### ISSUE THREAD

**Issue by bmsantos** [cbeust/kobalt#313]
Kobalt can't resolve dependency from private Maven Nexus server:

```
 → ./kobaltw --resolve com.graphql-java:graphql-java:3.1.1-SNAPSHOT --log 3
[Wrapper] Wrapper version: 0.910
[Wrapper]   Trying to install the same version 0.910 == 0.910, not overwriting the installed wrapper
[Wrapper] Launching [java, -Dfile.encoding=UTF-8, -jar, /Users/user/.kobalt/wrapper/dist/kobalt-0.910/kobalt/wrapper/kobalt-0.910.jar, --resolve, com.graphql-java:graphql-java:3.1.1-SNAPSHOT, --log, 3]
URL for core kobalt-plugin.xml: jar:file:/Users/user/.kobalt/wrapper/dist/kobalt-0.910/kobalt/wrapper/kobalt-0.910.jar!/META-INF/kobalt-core-plugin.xml
Parsed plugin XML file, found: kobalt
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.910

Saved /var/folders/s3/0_1vghg10td9wfcmfv1dql4m0000gn/T/kobalt2104156275562601936.kt
Script jar file: /Users/user/git/coco/oneheroweb/vertx/dx-graphql-vertx/.kobalt/build/preBuildScript.jar
Script jar file: /Users/user/git/coco/oneheroweb/vertx/dx-graphql-vertx/.kobalt/build/buildScript.jar
Created /var/folders/s3/0_1vghg10td9wfcmfv1dql4m0000gn/T/kobalt5089372965138956430.kt
Running build file Modified Build.kt jar: /Users/user/git/coco/oneheroweb/vertx/dx-graphql-vertx/.kobalt/build/buildScript.jar
  Build file is up to date
Found project dx-graphql-vertx in class class Kobalt709970655999192231Kt
Final list of repos:
  https://jcenter.bintray.com/
  http://repository.jetbrains.com/all/
  https://dl.bintray.com/ethauvin/maven/
  http://repo1.maven.org/maven2/
  file:/Users/user/.m2/repository/
  https://dl.bintray.com/kotlin/kotlin-eap
  http://nexus.private.com/repository/private/
Applying plug-in "Java"
Skipping nonexistent source directory ./src/main/java
Applying plug-in "Apt"
Applying plug-in "JvmCompiler"
Applying plug-in "Packaging"
Applying plug-in "Application"
Applying plug-in "Kobalt"
Applying plug-in "Publish"
Applying plug-in "Kotlin"
Skipping nonexistent source directory ./src/main/java
    Found task:clean method: class com.beust.kobalt.internal.JvmCompilerPlugin.taskClean
    Found task:doc method: class com.beust.kobalt.internal.JvmCompilerPlugin.taskJavadoc
    Found task:compileTest method: class com.beust.kobalt.internal.JvmCompilerPlugin.taskCompileTest
    Found task:compile method: class com.beust.kobalt.internal.JvmCompilerPlugin.taskCompile
    Found task:assemble method: class com.beust.kobalt.plugin.packaging.PackagingPlugin.doTaskAssemble
    Found task:install method: class com.beust.kobalt.plugin.packaging.PackagingPlugin.taskInstall
    Found task:run method: class com.beust.kobalt.plugin.application.ApplicationPlugin.taskRun
    Found task:checkVersions method: class com.beust.kobalt.plugin.KobaltPlugin.taskCheckVersions
    Found task:update method: class com.beust.kobalt.plugin.KobaltPlugin.taskUpdate
    Found task:generatePom method: class com.beust.kobalt.plugin.publish.PublishPlugin.taskGeneratePom
    Found task:publishToMavenLocal method: class com.beust.kobalt.plugin.publish.PublishPlugin.taskDeployToMavenLocal
    Found task:uploadBintray method: class com.beust.kobalt.plugin.publish.PublishPlugin.taskUploadBintray
    Found task:uploadGithub method: class com.beust.kobalt.plugin.publish.PublishPlugin.taskUploadGithub
Downloading: http://repo1.maven.org/maven2/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/maven-metadata.xml
Downloading: https://jcenter.bintray.com/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/maven-metadata.xml
Downloading: http://repository.jetbrains.com/all/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/maven-metadata.xml
Downloading: https://dl.bintray.com/ethauvin/maven/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/maven-metadata.xml
Downloading: file:/Users/user/.m2/repository/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/maven-metadata.xml
Downloading: https://dl.bintray.com/kotlin/kotlin-eap/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/maven-metadata.xml
Downloading: http://nexus.private.com/repository/private/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/maven-metadata.xml
Downloaded: http://nexus.private.com/repository/private/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/maven-metadata.xml (385 B at 0.2 KB/sec)
Downloading: https://jcenter.bintray.com/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.graphql-java:graphql-java:pom:3.1.1-20170113.201035-1 in  (https://jcenter.bintray.com/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at com.beust.kobalt.maven.aether.Aether.resolve(Aether.kt:216)
	at com.beust.kobalt.maven.aether.KobaltAether.resolveToArtifact(Aether.kt:117)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve(Aether.kt:106)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve$default(Aether.kt:103)
	at com.beust.kobalt.ResolveDependency.displayDependenciesFor(ResolveDependency.kt:33)
	at com.beust.kobalt.ResolveDependency.run(ResolveDependency.kt:28)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:195)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
Downloading: http://repository.jetbrains.com/all/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.graphql-java:graphql-java:pom:3.1.1-20170113.201035-1 in  (http://repository.jetbrains.com/all/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at com.beust.kobalt.maven.aether.Aether.resolve(Aether.kt:216)
	at com.beust.kobalt.maven.aether.KobaltAether.resolveToArtifact(Aether.kt:117)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve(Aether.kt:106)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve$default(Aether.kt:103)
	at com.beust.kobalt.ResolveDependency.displayDependenciesFor(ResolveDependency.kt:33)
	at com.beust.kobalt.ResolveDependency.run(ResolveDependency.kt:28)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:195)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
Downloading: https://dl.bintray.com/ethauvin/maven/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.graphql-java:graphql-java:pom:3.1.1-20170113.201035-1 in  (https://dl.bintray.com/ethauvin/maven/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at com.beust.kobalt.maven.aether.Aether.resolve(Aether.kt:216)
	at com.beust.kobalt.maven.aether.KobaltAether.resolveToArtifact(Aether.kt:117)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve(Aether.kt:106)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve$default(Aether.kt:103)
	at com.beust.kobalt.ResolveDependency.displayDependenciesFor(ResolveDependency.kt:33)
	at com.beust.kobalt.ResolveDependency.run(ResolveDependency.kt:28)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:195)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
Downloading: http://repo1.maven.org/maven2/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.graphql-java:graphql-java:pom:3.1.1-20170113.201035-1 in  (http://repo1.maven.org/maven2/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at com.beust.kobalt.maven.aether.Aether.resolve(Aether.kt:216)
	at com.beust.kobalt.maven.aether.KobaltAether.resolveToArtifact(Aether.kt:117)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve(Aether.kt:106)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve$default(Aether.kt:103)
	at com.beust.kobalt.ResolveDependency.displayDependenciesFor(ResolveDependency.kt:33)
	at com.beust.kobalt.ResolveDependency.run(ResolveDependency.kt:28)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:195)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
Downloading: file:/Users/user/.m2/repository/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.graphql-java:graphql-java:pom:3.1.1-20170113.201035-1 in  (file:/Users/user/.m2/repository/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at com.beust.kobalt.maven.aether.Aether.resolve(Aether.kt:216)
	at com.beust.kobalt.maven.aether.KobaltAether.resolveToArtifact(Aether.kt:117)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve(Aether.kt:106)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve$default(Aether.kt:103)
	at com.beust.kobalt.ResolveDependency.displayDependenciesFor(ResolveDependency.kt:33)
	at com.beust.kobalt.ResolveDependency.run(ResolveDependency.kt:28)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:195)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
Downloading: https://dl.bintray.com/kotlin/kotlin-eap/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.graphql-java:graphql-java:pom:3.1.1-20170113.201035-1 in  (https://dl.bintray.com/kotlin/kotlin-eap)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at com.beust.kobalt.maven.aether.Aether.resolve(Aether.kt:216)
	at com.beust.kobalt.maven.aether.KobaltAether.resolveToArtifact(Aether.kt:117)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve(Aether.kt:106)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve$default(Aether.kt:103)
	at com.beust.kobalt.ResolveDependency.displayDependenciesFor(ResolveDependency.kt:33)
	at com.beust.kobalt.ResolveDependency.run(ResolveDependency.kt:28)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:195)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
Downloading: http://nexus.private.com/repository/private/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom
Downloaded: http://nexus.private.com/repository/private/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom (2 KB at 16.1 KB/sec)
Downloaded artifact com.graphql-java:graphql-java:pom:3.1.1-20170113.201035-1 from  (http://nexus.private.com/repository/private/, default, releases+snapshots)
Downloading: https://jcenter.bintray.com/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.jar
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.graphql-java:graphql-java:jar:3.1.1-20170113.201035-1 in  (https://jcenter.bintray.com/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:373)
	at com.beust.kobalt.maven.aether.Aether.resolve(Aether.kt:216)
	at com.beust.kobalt.maven.aether.KobaltAether.resolveToArtifact(Aether.kt:117)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve(Aether.kt:106)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve$default(Aether.kt:103)
	at com.beust.kobalt.ResolveDependency.displayDependenciesFor(ResolveDependency.kt:33)
	at com.beust.kobalt.ResolveDependency.run(ResolveDependency.kt:28)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:195)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
*****
***** ERROR Couldn't resolve com.graphql-java:graphql-java:3.1.1-SNAPSHOT
*****
com.beust.kobalt.KobaltException: Couldn't resolve com.graphql-java:graphql-java:3.1.1-SNAPSHOT
	at com.beust.kobalt.maven.aether.KobaltAether.resolve(Aether.kt:110)
	at com.beust.kobalt.maven.aether.KobaltAether.resolve$default(Aether.kt:103)
	at com.beust.kobalt.ResolveDependency.displayDependenciesFor(ResolveDependency.kt:33)
	at com.beust.kobalt.ResolveDependency.run(ResolveDependency.kt:28)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:195)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
```

Reproducing steps:

Build a new version of a given artifact and publish the SNAPSHOT to the maven repository.
Remove all references to the SNAPSHOT artifact in local maven repo as well as in kobalt cache.
Build the project and it should fail.

Interesting is the fact that, neither ./kobalt/cache or .m2/repository include the downloaded pom.xml.

Other details, in case it matters:
Nexus Repository Manager: 3.0.1-01
Pom contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.graphql-java</groupId>
  <artifactId>graphql-java</artifactId>
  <version>3.1.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>antlr4-runtime</artifactId>
      <version>4.5.1</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.12</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.spotify</groupId>
      <artifactId>completable-futures</artifactId>
      <version>0.3.0</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <name>graphql-java</name>
  <description>GraphqL Java</description>
  <url>https://github.com/graphql-java/graphql-java</url>
  <scm>
    <url>https://github.com/graphql-java/graphql-java</url>
    <connection>https://github.com/graphql-java/graphql-java</connection>
    <developerConnection>https://github.com/graphql-java/graphql-java</developerConnection>
  </scm>
  <licenses>
    <license>
      <name>MIT</name>
      <url>https://github.com/graphql-java/graphql-java/blob/master/LICENSE.md</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>andimarek</id>
      <name>Andreas Marek</name>
    </developer>
  </developers>
</project>
```

**Comment by cbeust** [comment]
I don't follow: where exactly is that dependency `com.graphql-java:graphql-java:3.1.1-SNAPSHOT `?

I'm not seeing it in https://dl.bintray.com/ethauvin/maven/

**Comment by bmsantos** [comment]
It's a dependency pushed into a corporate maven Nexus server (maven repo).

**Comment by bmsantos** [comment]
Here's an example of the repo's configuration in Build.kt:

```kotlin
val r = repos(
        "http://nexus.company.com/repository/company",
        localMaven(),
        "https://dl.bintray.com/ethauvin/maven"
)
```

**Comment by cbeust** [comment]
Can you show the content of that repo in the `graphql` directory?

Maybe zip it and attach it here so I can unzip it in my own localMavenRepo?

**Comment by bmsantos** [comment]
Here are the directory contents for ```.m2/repository/com/graphql-java/3.0.0-SNAPSHOT.zip```:

[com.graphql-java.3.0.0-SNAPSHOT.zip](https://github.com/cbeust/kobalt/files/718293/com.graphql-java.3.0.0-SNAPSHOT.zip)

**Comment by bmsantos** [comment]
I'm going to try to get the system admins to zip the contents in the Nexus repository.

**Comment by bmsantos** [comment]
Here's my local build.

[localMaven-com.graphql-java_graphql-java_3.1.1-SNAPSHOT.zip](https://github.com/cbeust/kobalt/files/720928/localMaven-com.graphql-java_graphql-java_3.1.1-SNAPSHOT.zip)

**Comment by cbeust** [comment]
I unzipped that file in `~/.kobalt/cache/localMavenRepo/com/.../3.1.1-SNAPSHOT` and then ran:

```
./kobaltw --resolve com.graphql-java:graphql-java:3.1.1-SNAPSHOT --log 2
```

It worked:

```
Downloaded: file:///Users/cedricbeust/.kobalt/localMavenRepo/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-SNAPSHOT.jar (368 KB at 40792.4 KB/sec)
Downloaded artifact com.graphql-java:graphql-java:jar:3.1.1-SNAPSHOT from  (file:///Users/cedricbeust/.kobalt/localMavenRepo/, default, releases+snapshots)

...

╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                         com.graphql-java:graphql-java:jar:3.1.1-SNAPSHOT                                ║
║                          (file:///Users/cedricbeust/.kobalt/localMavenRepo/, default, releases+snapshots)               ║
║           /Users/cedricbeust/.kobalt/cache/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-SNAPSHOT.jar ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

Can you try wiping your whole cache? (or just renaming it if you don't want to lose everything)

```
rm -rf ~/.kobalt/cache
```

**Comment by bmsantos** [comment]
It works just fine when I build the dependency locally and load it from my local repository.
The issue is that the company has a Maven Nexus repository from Sonatype and when Kobalt tries to fetch the dependency from Nexus, finds it and downloads it but then proceeds to look into JCenter where it does not exist. When this happens it seems to discard it as shown in the logs above:

```
Downloading: http://nexus.private.com/repository/private/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom
Downloaded: http://nexus.private.com/repository/private/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.pom (2 KB at 16.1 KB/sec)
Downloaded artifact com.graphql-java:graphql-java:pom:3.1.1-20170113.201035-1 from  (http://nexus.private.com/repository/private/, default, releases+snapshots)
Downloading: https://jcenter.bintray.com/com/graphql-java/graphql-java/3.1.1-SNAPSHOT/graphql-java-3.1.1-20170113.201035-1.jar
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.graphql-java:graphql-java:jar:3.1.1-20170113.201035-1 in  (https://jcenter.bintray.com/)
```

**Comment by cbeust** [comment]
So I'm not quite sure if there's any action item for me here.

Can I just unzip your repo in my private repo and see the failure? If not, any way I can reproduce it?

If not, I'll just close this.

Thanks.

**Comment by bmsantos** [comment]
@cbeust, I'm going to close this issue for now. Admins have not yet come back to me on this (large companies are like this sometimes). If I get further details on this I will then get back to you.

Thanks
