### ISSUE TITLE
IllegalStateException when compiling with Kotlin 1.1-beta-22

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#319]
```
*****
***** ERROR Error: java.lang.IllegalStateException:
*****
java.util.concurrent.ExecutionException: java.lang.IllegalStateException:
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.beust.kobalt.internal.DynamicGraphExecutor.run2(DynamicGraph.kt:236)
	at com.beust.kobalt.internal.DynamicGraphExecutor.run(DynamicGraph.kt:200)
	at com.beust.kobalt.internal.ParallelProjectRunner.runProjects(ParallelProjectRunner.kt:105)
	at com.beust.kobalt.internal.TaskManager.runTargets(TaskManager.kt:104)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:205)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
Caused by: java.lang.IllegalStateException:
	at com.beust.kobalt.misc.NewRunCommand$Companion$DEFAULT_ERROR$1.invoke(NewRunCommand.kt:53)
	at com.beust.kobalt.misc.NewRunCommand$Companion$DEFAULT_ERROR$1.invoke(NewRunCommand.kt:46)
	at com.beust.kobalt.misc.NewRunCommand.invoke(NewRunCommand.kt:92)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.invokeCompilerInSeparateProcess(KotlinCompiler.kt:115)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.compile(KotlinCompiler.kt:78)
	at com.beust.kobalt.internal.JvmCompiler.doCompile(JvmCompiler.kt:37)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler.compile(KotlinCompiler.kt:302)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile(KotlinCompiler.kt:325)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin$KotlinCompiler.compile(KotlinPlugin.kt:88)
	at com.beust.kobalt.api.CompilerDescription.compile(ICompilerContributor.kt:59)
	at com.beust.kobalt.internal.CompilerUtils.invokeCompiler(CompilerUtils.kt:58)
	at com.beust.kobalt.internal.CompilerUtils.invokeCompiler(CompilerUtils.kt:41)
	at com.beust.kobalt.internal.JvmCompilerPlugin$doTaskCompile$3.invoke(JvmCompilerPlugin.kt:186)
	at com.beust.kobalt.internal.JvmCompilerPlugin$doTaskCompile$3.invoke(JvmCompilerPlugin.kt:29)
	at com.beust.kobalt.internal.CollectionUtilsKt.doWhile(CollectionUtils.kt:9)
	at com.beust.kobalt.internal.JvmCompilerPlugin.doTaskCompile(JvmCompilerPlugin.kt:185)
	at com.beust.kobalt.internal.JvmCompilerPlugin.doTaskCompile(JvmCompilerPlugin.kt:145)
	at com.beust.kobalt.internal.JvmCompilerPlugin.access$doTaskCompile(JvmCompilerPlugin.kt:29)
	at com.beust.kobalt.internal.JvmCompilerPlugin$taskCompile$3.invoke(JvmCompilerPlugin.kt:140)
	at com.beust.kobalt.internal.JvmCompilerPlugin$taskCompile$3.invoke(JvmCompilerPlugin.kt:29)
	at com.beust.kobalt.internal.IncrementalManager$toIncrementalTaskClosure$1.invoke(IncrementalManager.kt:159)
	at com.beust.kobalt.internal.IncrementalManager$toIncrementalTaskClosure$1.invoke(IncrementalManager.kt:26)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:270)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:268)
	at com.beust.kobalt.internal.ParallelProjectRunner$runProjects$ProjectTask.call(ParallelProjectRunner.kt:57)
	at com.beust.kobalt.internal.ParallelProjectRunner$runProjects$factory$1$createWorkers$result$1$1.call(ParallelProjectRunner.kt:84)
	at com.beust.kobalt.internal.ParallelProjectRunner$runProjects$factory$1$createWorkers$result$1$1.call(ParallelProjectRunner.kt:80)
	at com.beust.kobalt.internal.DynamicGraphExecutor$run2$$inlined$map$lambda$1.call(DynamicGraph.kt:224)
	at com.beust.kobalt.internal.DynamicGraphExecutor$run2$$inlined$map$lambda$1.call(DynamicGraph.kt:214)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cbeust** [comment]
Closed? Not a bug?

**Comment by pabl0rg** [comment]
It seems to be related to setting a different compiler version than the default, should I move this over to #314 ?

**Comment by cbeust** [comment]
I'm not sure, but if you can give me a way to reproduce this, I can look into it.

If you specify a different compiler version with `kobaltCompilerVersion`, Kobalt should still work (it will fork the compilation phase in a totally different JVM so there should be no conflict).
