### ISSUE TITLE
StackOverflowError when resolving cyclic dependencies

### ISSUE THREAD

**Issue by foxlegend** [cbeust/kobalt#339]
Hello,

When invoking the `run` task for a project containing a dependency cycle, I had a `StackOverflowError` in the `KobaltMavenResolver` class:

```
───── kagen-api:run
*****
***** ERROR Error: null
*****
java.lang.StackOverflowError
	at org.codehaus.plexus.interpolation.reflection.ReflectionValueExtractor.getClassMap(ReflectionValueExtractor.java:119)
	at org.codehaus.plexus.interpolation.reflection.ReflectionValueExtractor.evaluate(ReflectionValueExtractor.java:90)
	at org.codehaus.plexus.interpolation.ObjectBasedValueSource.getValue(ObjectBasedValueSource.java:64)
	at org.codehaus.plexus.interpolation.PrefixedValueSourceWrapper.getValue(PrefixedValueSourceWrapper.java:129)
	at org.codehaus.plexus.interpolation.AbstractDelegatingValueSource.getValue(AbstractDelegatingValueSource.java:44)
	at org.codehaus.plexus.interpolation.StringSearchInterpolator.interpolate(StringSearchInterpolator.java:198)
	at org.codehaus.plexus.interpolation.StringSearchInterpolator.interpolate(StringSearchInterpolator.java:217)
	at org.codehaus.plexus.interpolation.StringSearchInterpolator.interpolate(StringSearchInterpolator.java:122)
	at org.apache.maven.model.interpolation.AbstractStringBasedModelInterpolator.interpolateInternal(AbstractStringBasedModelInterpolator.java:227)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction.interpolate(StringSearchModelInterpolator.java:141)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction.access$300(StringSearchModelInterpolator.java:95)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction$StringField.doInterpolate(StringSearchModelInterpolator.java:349)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction$CacheField.interpolate(StringSearchModelInterpolator.java:301)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction$CacheItem.interpolate(StringSearchModelInterpolator.java:274)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction.traverseObjectWithParents(StringSearchModelInterpolator.java:158)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction.run(StringSearchModelInterpolator.java:132)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator.interpolateObject(StringSearchModelInterpolator.java:78)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator.interpolateModel(StringSearchModelInterpolator.java:61)
	at org.apache.maven.model.building.DefaultModelBuilder.interpolateModel(DefaultModelBuilder.java:769)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:385)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:544)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:528)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:418)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:513)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:467)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:513)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:467)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:513)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:467)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:263)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:350)
	at com.beust.kobalt.maven.aether.KobaltMavenResolver.resolve(KobaltMavenResolver.kt:38)
	at com.beust.kobalt.maven.aether.KobaltMavenResolver.resolveToIds(KobaltMavenResolver.kt:49)
	at com.beust.kobalt.maven.aether.KobaltMavenResolver.resolveToIds(KobaltMavenResolver.kt:58)
	at com.beust.kobalt.maven.aether.KobaltMavenResolver.resolveToIds(KobaltMavenResolver.kt:58)
	at com.beust.kobalt.maven.aether.KobaltMavenResolver.resolveToIds(KobaltMavenResolver.kt:58)
	at com.beust.kobalt.maven.aether.KobaltMavenResolver.resolveToIds(KobaltMavenResolver.kt:58)
	at com.beust.kobalt.maven.aether.KobaltMavenResolver.resolveToIds(KobaltMavenResolver.kt:58)
...
```

I tried to investigate and, when debugging kobalt, that there was a Maven dependency cycle from one of "org.springframework.boot:spring-boot-starter:jar:1.5.2.RELEASE" artifact children, and more accurately something like that:
```
... -> xstream:1.4.7 -> dom4j:1.6.1 -> jaxen:1.1-beta-6 -> dom4j:1.5.2 -> jaxen:1.1-beta4 -> dom4j:1.5.2 -> jaxen:1.1-beta4 -> ....
```
Here the cyclic dependency is between `dom4j` and `jaxen` which leads to the `StackOverflowError` above. I think there is a missing terminal condition in the recursive function `resolveToIds` which should stop recursion when the dependency was already resolved.

Do not hesitate if you need more information about this issue!

**Comment by cbeust** [comment]
This should be enough information for me to reproduce it, I'll get back to you. Thanks for the details!

**Comment by cbeust** [comment]
Looking at the stack trace more closely, it worries me that this is happening in Aether and not in Kobalt.

**Comment by foxlegend** [comment]
Ok! As I'm interested to contribute to kobalt, I can investigate more deeply the issue if you want and propose something for such a case ?

**Comment by cbeust** [comment]
No luck reproducing so far: I added this dependency to my `compile` and my build succeeded (after downloading the whole Internet of course, this is Spring we're talking about). See below.

Do you have a project I can clone to reproduce the problem?

```
───── klaxon:compile
Downloaded artifact org.springframework.boot:spring-boot-starter:pom:1.5.2.RELEASE from  (https://jcenter.bintray.com/, default, releases+snapshots)
Downloaded artifact org.springframework.boot:spring-boot-starters:pom:1.5.2.RELEASE from  (https://jcenter.bintray.com/, default, releases+snapshots)
Downloaded artifact org.springframework.boot:spring-boot-parent:pom:1.5.2.RELEASE from  (https://jcenter.bintray.com/, default, releases+snapshots)
Downloaded artifact org.springframework.boot:spring-boot-dependencies:pom:1.5.2.RELEASE from  (https://jcenter.bintray.com/, default, releases+snapshots)
Downloaded artifact com.fasterxml.jackson:jackson-bom:pom:2.8.7 from  (https://jcenter.bintray.com/, default, releases+snapshots)
Downloaded artifact com.fasterxml.jackson:jackson-parent:pom:2.8 from  (https://jcenter.bintray.com/, default, releases+snapshots)
...
Downloaded artifact org.springframework.security:spring-security-crypto:jar:4.2.2.RELEASE from  (https://jcenter.bintray.com/, default, releases+snapshots)
  Kotlin 1.1.0 compiling 8 files
  Actual files that needed to be compiled: 7
  Java compiling 1 file
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
───── klaxon:assemble
  Created ./kobaltBuild/libs/klaxon-0.29.jar
  Created ./kobaltBuild/libs/klaxon-0.29-sources.jar
  Created ./kobaltBuild/libs/klaxon-0.29-javadoc.jar
  Created ./kobaltBuild/libs/klaxon-0.29.pom

Thread report
╔════════════════════════════════════════╗
║  Time (sec) ║ Thread 14                ║
╠════════════════════════════════════════╣
║  0          ║ klaxon                   ║
║  214        ║ klaxon (214)             ║
╚════════════════════════════════════════╝
          ╔══════════════════════════════════════════════════════════╗
          ║  Project                       ║ Build status ║ Time     ║
          ╠══════════════════════════════════════════════════════════╣
          ║  klaxon                        ║ SUCCESS      ║ 214.32   ║
          ╚══════════════════════════════════════════════════════════╝
```

**Comment by foxlegend** [comment]
The problem does not appear with the `compile` or `assemble` tasks, but only with the `run` one. I have no clue about differences in dependencies resolution among each task type however :/

To have an example, I just pushed on one of my repository: [https://github.com/foxlegend/kagen](https://github.com/foxlegend/kagen).
You can try to use the `kagen-api:run` task which would boot a webserver using spring boot.

BTW, when debugging the `KobaltMavenResolver` class, I found that Aether detects the cycle (thanks to the Aether artifact `cycles` attribute).

**Comment by cbeust** [comment]
I made some progress and now seeing this error:

```
Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.util.Assert.notEmpty(Assert.java:277)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:153)
```

This looks like more a problem on your app's end and not Kobalt's?

Also, note that since you specified `@JvmStatic`, your main application class is now `Application` and not `ApplicationKt`.

**Comment by cbeust** [comment]
Update (`./kobaltw --update`) and you should now be able to run your app, at least until it dies with the exception above.

**Comment by foxlegend** [comment]
Thank you a lot for the issue resolution! :) 

Yes, the exception is more relevant to the way the application is ran and not Kobalt's: I just commited something producing the issue.

**Comment by cbeust** [comment]
Let me know if you encounter more problems!

**Comment by cbeust** [comment]
Let me know if you encounter more problem and feel free to join us on Slack at #kobalt!
