### ISSUE TITLE
Exception on --update requiring rm -rf .kobalt

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#354]
```
$ ./kobaltw --update
              __ __           __              __   __
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  1.0.26

Couldn't compile file: org.jetbrains.kotlin.cli.jvm.compiler.CompileEnvironmentException: Invalid jar path K:\kotlin\kobalt-maven-local\example\.kobalt\build\preBuildScript.jar
        at org.jetbrains.kotlin.cli.jvm.compiler.CompileEnvironmentUtil.writeToJar(CompileEnvironmentUtil.java:110)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.writeOutput(KotlinToJVMBytecodeCompiler.kt:90)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileBunchOfSources(KotlinToJVMBytecodeCompiler.kt:213)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:203)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:191)
        at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1$invokeCompilerDirectly$result$duration$1.invoke(KotlinCompiler.kt:229)
        at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1$invokeCompilerDirectly$result$duration$1.invoke(KotlinCompiler.kt:40)
        at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
        at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.invokeCompilerDirectly(KotlinCompiler.kt:228)

        at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.compile(KotlinCompiler.kt:92)
        at com.beust.kobalt.internal.JvmCompiler.doCompile(JvmCompiler.kt:37)
        at com.beust.kobalt.plugin.kotlin.KotlinCompiler.compile(KotlinCompiler.kt:388)
        at com.beust.kobalt.plugin.kotlin.KConfiguration.compile(KotlinCompiler.kt:414)
        at com.beust.kobalt.plugin.kotlin.KConfiguration.compile$default(KotlinCompiler.kt:411)
        at com.beust.kobalt.app.ParsedBuildFile.generateJarFile(ParsedBuildFile.kt:176)
        at com.beust.kobalt.app.ParsedBuildFile.initPluginUrls(ParsedBuildFile.kt:141)
        at com.beust.kobalt.app.ParsedBuildFile.<init>(ParsedBuildFile.kt:44)
        at com.beust.kobalt.app.BuildFileCompiler.parseBuildFile(BuildFileCompiler.kt:181)
        at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:89)
        at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:75)
        at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles$default(BuildFileCompiler.kt:49)
        at com.beust.kobalt.app.ProjectFinder.initForBuildFile(ProjectFinder.kt:20)
        at com.beust.kobalt.Main.runWithArgs(Main.kt:165)
        at com.beust.kobalt.Main.run(Main.kt:112)
        at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
        at com.beust.kobalt.MainKt.main(Main.kt:27)
Caused by: java.io.FileNotFoundException: K:\kotlin\kobalt-maven-local\example\.kobalt\build\preBuildScript.jar (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at org.jetbrains.kotlin.cli.jvm.compiler.CompileEnvironmentUtil.writeToJar(CompileEnvironmentUtil.java:105)
        ... 26 more
```
[example.zip](https://github.com/cbeust/kobalt/files/870533/example.zip)

**Comment by ethauvin** [comment]
No longer an issue with 1.0.51.
