### ISSUE TITLE
Update fails with exception

### ISSUE THREAD

**Issue by codeslubber** [cbeust/kobalt#39]
Just running ./kobaltw --update as suggested results in:

```
/usr/local/kobalt/kobaltw --update
Downloading kobalt-0.267.zip
Exception in thread "main" java.lang.IllegalStateException: Couldn't download https://dl.bintray.com/cbeust/generic/
	at kotlin.PreconditionsKt__PreconditionsKt.error(Preconditions.kt:142)
	at kotlin.PreconditionsKt.error(Unknown Source)
	at com.beust.kobalt.wrapper.Wrapper.install(Wrapper.kt:136)
	at com.beust.kobalt.wrapper.Wrapper.installAndLaunchMain(Wrapper.kt:40)
```

Once this fails, tool is unusable until the dir off home is wiped:

```
/usr/local/kobalt/kobaltw 
[Wrapper error] *** No file to download. Server replied HTTP code: 404
Exception in thread "main" java.io.FileNotFoundException: /Users/robwilliams/.kobalt/wrapper/dist/kobalt-0.267.zip (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
```

This is on a mac running 10.11.

**Comment by cbeust** [comment]
You must have hit the download server as I was uploading it...

0.268 is up, can you try it and report back?

**Comment by codeslubber** [comment]
Sure. So I torched the ~/.kobalt dir and get this now:

```
/usr/local/kobalt/kobaltw --update
[Wrapper error] *** No file to download. Server replied HTTP code: 404
Exception in thread "main" java.io.FileNotFoundException: /Users/robwilliams/.kobalt/wrapper/dist/kobalt-0.233.zip (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
```

?

**Comment by cbeust** [comment]
Mmmh this is weird. I just tried the following in an empty directory:

```
$ mkdir 0.268
$ cd 0.268
$ unzip ~/Downloads/kobalt-0.268.zip
$ chmod 755 kobaltw
$ cd ..
$ 0.268/kobaltw --init
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.268

Couldn't identify project, not generating any build file
BUILD SUCCESSFUL (0 seconds)
```

Can you try these steps too?

**Comment by codeslubber** [comment]
Uh something crazy happened. Download did not have a zip inside or Finder opened it??

```
find .
.
./.DS_Store
./kobalt
./kobalt/.DS_Store
./kobalt/wrapper
./kobalt/wrapper/kobalt-0.268.jar
./kobalt/wrapper/kobalt-wrapper.jar
./kobaltw
```

?

**Comment by cbeust** [comment]
Not sure I understand...

**Comment by codeslubber** [comment]
Ok, so that worked, but here's what threw me. Going back to one of my projects and simply running assemble again brings this:

```
           / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_  
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  0.268

info: PERF: INIT: Compiler initialized in 587 ms
info: PERF: ANALYZE: 1 files (3 lines) in 823 ms
info: PERF: GENERATE: 1 files (3 lines) in 99 ms
info: PERF: INIT: Compiler initialized in 145 ms
info: PERF: ANALYZE: 1 files (38 lines) in 169 ms
info: PERF: GENERATE: 1 files (38 lines) in 73 ms
          ╔═════════════════════════════╗
          ║ Building project projectbot ║
          ╚═════════════════════════════╝
========== projectbot:clean
========== projectbot:compile
exception: java.lang.NoClassDefFoundError: jline/console/ConsoleReader
	at org.jetbrains.kotlin.cli.jvm.repl.reader.ConsoleReplCommandReader.<init>(ConsoleReplCommandReader.kt:25)
	at org.jetbrains.kotlin.cli.jvm.repl.ReplFromTerminal.createCommandReader(ReplFromTerminal.java:101)
	at org.jetbrains.kotlin.cli.jvm.repl.ReplFromTerminal.<init>(ReplFromTerminal.java:92)
	at org.jetbrains.kotlin.cli.jvm.repl.ReplFromTerminal.run(ReplFromTerminal.java:247)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:125)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:174)
```

Seems that kobalt copies itself into the project dir, so if you update the remote copy (I have it in /usr/local), how does it update the project copy? Should I run init again? or --update?

Sorry these are probably stupid questions and maybe are answered in the docs.

**Comment by codeslubber** [comment]
Strange thing is it does proceed to build the jar. Rerunning init, the docs say, should not result in your build file being remade, so I did that, but same result.

**Comment by cbeust** [comment]
Somebody else reported the jline problem, can you `rm -rf ~/.kobalt/repository` and try to build again? It might have gotten corrupt with 0.267.

**Comment by codeslubber** [comment]
Same thing..

**Comment by cbeust** [comment]
Can you include the full stack trace?

**Comment by codeslubber** [comment]
Went into the subdir of another project and weird, it tried to install 0.267.

```
/usr/local/kobalt/kobaltw assemble
Downloading https://github.com/cbeust/kobalt/releases/download/0.267/kobalt-0.267.zip 100.0%
[Wrapper] Downloaded https://github.com/cbeust/kobalt/releases/download/0.267/kobalt-0.267.zip
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.267

Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/kobalt/plugin/packaging/Package
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at com.beust.kobalt.kotlin.BuildFileCompiler.parseBuildScriptJarFile(BuildFileCompiler.kt:234)
	at com.beust.kobalt.kotlin.BuildFileCompiler.access$parseBuildScriptJarFile(BuildFileCompiler.kt:32)
	at com.beust.kobalt.kotlin.BuildFileCompiler.findProjects(BuildFileCompiler.kt:81)
	at com.beust.kobalt.kotlin.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:59)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:155)
	at com.beust.kobalt.Main.access$runWithArgs(Main.kt:46)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:97)
	at com.beust.kobalt.Main$run$seconds$1.invoke(Main.kt:46)
	at com.beust.kobalt.misc.BenchmarksKt.benchmark(Benchmarks.kt:5)
	at com.beust.kobalt.Main.run(Main.kt:95)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:43)
	at com.beust.kobalt.MainKt.main(Main.kt:25)
Caused by: java.lang.ClassNotFoundException: com.beust.kobalt.plugin.packaging.Package
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
```

Somewhere it's thinking we are still using that version.

**Comment by cbeust** [comment]
Use ./kobaltw, which will pick the version in {pwd}/wrapper/kobalt-wrapper.properties. That might be part of the problem you're seeing.

It might also be:

![image](https://cloud.githubusercontent.com/assets/92322/11220965/62944736-8d17-11e5-862c-c99adbeb5eaa.png)

**Comment by codeslubber** [comment]
Ok, great, that makes sense. I was just thinking if I update using a zip, that has to go somewhere before ending up in ~/.kobalt no?

**Comment by cbeust** [comment]
The process is:

- Download the .zip
- Copy .kobaltw in your project
- From now on, you only ever use $project/kobaltw and you upgrade by editing $project/wrapper/kobalt-wrapper.properties.

You should not have to touch anything in the .zip from that point on (unless you want to reinstall from scratch).

**Comment by codeslubber** [comment]
Right. I was not going back to the /usr/local version to run the build. I was doing that inside IntelliJ. I went back to it because the update command failed.

**Comment by cbeust** [comment]
So all good for now?

**Comment by codeslubber** [comment]
Uh no. I have fallen into a pit here. I got 0.268 working in the one project, but the ConsoleReader thing still comes up at the command line. I go inside IDEA and it syncs the build file, and, it downloads the Spek jar, but it doesn't see it so it refuses to build or run the tests inside the project. Of course, this was all working a moment before trying to update to 0.268. I guess because of that exception, even though it says it's making the jar, it's probably not completing successfully..?

**Comment by codeslubber** [comment]
Here is the latest complete (so you can see I am following orders and using the wrapper from the project dir :) ):

```
./kobaltw assemble
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.268

          ╔══════════════════════╗
          ║ Building project FRC ║
          ╚══════════════════════╝
========== FRC:clean
========== FRC:compile
exception: java.lang.NoClassDefFoundError: jline/console/ConsoleReader
	at org.jetbrains.kotlin.cli.jvm.repl.reader.ConsoleReplCommandReader.<init>(ConsoleReplCommandReader.kt:25)
	at org.jetbrains.kotlin.cli.jvm.repl.ReplFromTerminal.createCommandReader(ReplFromTerminal.java:101)
	at org.jetbrains.kotlin.cli.jvm.repl.ReplFromTerminal.<init>(ReplFromTerminal.java:92)
	at org.jetbrains.kotlin.cli.jvm.repl.ReplFromTerminal.run(ReplFromTerminal.java:247)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:125)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:174)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:135)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.doMainNoExit(CLICompiler.java:240)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.compile(KotlinCompiler.kt:49)
	at com.beust.kobalt.internal.JvmCompiler.doCompile(JvmCompiler.kt:42)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler.compile(KotlinCompiler.kt:76)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile(KotlinCompiler.kt:98)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.compilePrivate(KotlinPlugin.kt:81)
	at com.beust.kobalt.plugin.kotlin.KotlinPlugin.taskCompile(KotlinPlugin.kt:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.beust.kobalt.Plugins$applyPlugins$1$7$1$result$1.invoke(Plugins.kt:104)
	at com.beust.kobalt.Plugins$applyPlugins$1$7$1$result$1.invoke(Plugins.kt:24)
	at com.beust.kobalt.api.IPlugin$addTask$1.call(IPlugin.kt:33)
	at com.beust.kobalt.api.IPlugin$addTask$1.call(IPlugin.kt:31)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:214)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:201)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: jline.console.ConsoleReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

========== FRC:assemble
  Created ./kobaltBuild/libs/FRC-0.1.jar
```

Seriously, sorry to be such a nuisance. I just wanted to make sure I could pull updates at will.

**Comment by cbeust** [comment]
Can you join us on slack? Will be easier to chat.

-- 
Cédric

**Comment by codeslubber** [comment]
Sure. I tried to find the channel a week or so ago. Where is it? I found Kotlinlang...
