### ISSUE TITLE
NoSuchFileException when kobalt tries to rename .tmp files

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#77]
With Kobalt plugin 1.3.1 (and kobalt 0.338) I continue to see errors like this one.  I would guess that one thread has already renamed this file when another is trying to rename it again (from .jar.tmp to .jar)

<img width="586" alt="screen shot 2015-12-14 at 9 13 43 pm" src="https://cloud.githubusercontent.com/assets/10501896/11801053/c35bcfa8-a2a7-11e5-9803-7ded960e71b2.png">

**Comment by pabl0rg** [comment]
This also happens (v0.357) using the command line.  Here's an example.  The file does download and after running this, it exists at /Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-SNAPSHOT.jar

L/12:13:40.961 [K-JvmCompiler}-39] ArtifactFetcher -   Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-20151222.164643-1770.jar
L/12:13:40.961 [K-JvmCompiler}-39] ArtifactFetcher -      to /Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-SNAPSHOT.jar
W/12:13:40.971 [K-JvmCompiler}-39] ArtifactFetcher - ***** WARNING MD5 not matching for https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-20151222.164643-1770.jar
L/12:13:41.488 [K-Dependency-27] ArtifactFetcher - Done downloading, renaming /Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-SNAPSHOT.jar.tmp to /Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-SNAPSHOT.jar
E/12:13:41.489 [K-Dependency-27] KobaltExecutor - ***** E java.nio.file.NoSuchFileException: /Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-SNAPSHOT.jar.tmp
E/12:13:41.489 [main] DynamicGraphExecutor - ***** E Error: java.nio.file.NoSuchFileException: /Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-SNAPSHOT.jar.tmp
java.util.concurrent.ExecutionException: java.nio.file.NoSuchFileException: /Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-SNAPSHOT.jar.tmp

**Comment by pabl0rg** [comment]
I meant to include the stack trace

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.beust.kobalt.maven.DependencyManager.transitiveClosure(DependencyManager.kt:64)
	at com.beust.kobalt.maven.DependencyManager.transitiveClosure(DependencyManager.kt:55)
	at com.beust.kobalt.maven.DependencyManager.calculateDependencies(DependencyManager.kt:25)
	at com.beust.kobalt.plugin.packaging.JarGenerator.findIncludedFiles(JarGenerator.kt:58)
	at com.beust.kobalt.plugin.packaging.JarGenerator.generateJar(JarGenerator.kt:76)
	at com.beust.kobalt.plugin.packaging.PackagingPlugin.doTaskAssemble(PackagingPlugin.kt:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.beust.kobalt.internal.TaskManager$toTaskAnnotation$1.invoke(TaskManager.kt:238)
	at com.beust.kobalt.internal.TaskManager$toTaskAnnotation$1.invoke(TaskManager.kt:20)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:312)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:310)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:341)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:327)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/0.1-SNAPSHOT/kotlin-stdlib-0.1-SNAPSHOT.jar.tmp
