### ISSUE TITLE
if fatJar assemble fails, should report build failure and not leave/create a jar

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#82]
When I ran (v0.360)
./kobaltw --dev --log 3 assemble

With an incorrectly zipped jar file dependency (./lib/jenkov-mrpersister-stsa-4.0.0.jar), the assemble failed, but the Kobalt still reported build success and my project's incomplete fat jar was left in ./kobaltBuild/libs so that when I re-ran the command, Kobalt said there was nothing left to do b/c code had not changed and the jar already existed.

Here's the output:

L/23:26:49.483 [K-DynamicGraphExecutor-12] Companion - Writing contents of jar file ./lib/jenkov-mrpersister-stsa-4.0.0.jar
E/23:26:49.485 [main] DynamicGraphExecutor - ***** E Error: invalid entry compressed size (expected 5683 but got 5652 bytes)
java.util.zip.ZipException: invalid entry compressed size (expected 5683 but got 5652 bytes)
	at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:268)
	at com.beust.kobalt.misc.JarUtils$Companion.addEntry(JarUtils.kt:100)
	at com.beust.kobalt.misc.JarUtils$Companion.access$addEntry(JarUtils.kt:15)
	at com.beust.kobalt.misc.JarUtils$Companion.addSingleFile(JarUtils.kt:70)
	at com.beust.kobalt.misc.JarUtils$Companion.addFiles(JarUtils.kt:27)
	at com.beust.kobalt.misc.JarUtils$Companion.addFiles$default(JarUtils.kt:25)
	at com.beust.kobalt.plugin.packaging.PackagingPlugin$Companion.generateArchive(PackagingPlugin.kt:94)
	at com.beust.kobalt.plugin.packaging.JarGenerator.generateJar(JarGenerator.kt:87)
	at com.beust.kobalt.plugin.packaging.PackagingPlugin.doTaskAssemble(PackagingPlugin.kt:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.beust.kobalt.internal.TaskManager$toTaskAnnotation$1.invoke(TaskManager.kt:246)
	at com.beust.kobalt.internal.TaskManager$toTaskAnnotation$1.invoke(TaskManager.kt:21)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:320)
	at com.beust.kobalt.internal.TaskManager$addTask$1.call(TaskManager.kt:318)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:354)
	at com.beust.kobalt.internal.TaskWorker$call$$inlined$forEach$lambda$1.invoke(TaskManager.kt:335)
	at com.beust.kobalt.misc.BenchmarksKt.benchmarkMillis(Benchmarks.kt:5)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:348)
	at com.beust.kobalt.internal.TaskWorker.call(TaskManager.kt:335)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
L/23:26:49.486 [main] DynamicGraph -     freeNodes: []
L/23:26:49.487 [main] DynamicGraph -     freeNodes: []
L/23:26:49.487 [main] DynamicGraph -     freeNodes: []
L/23:26:49.487 [main] Main - BUILD SUCCESSFUL (1 seconds)
Juans-MacBook-Pro backend-1.7> rm ./kobaltBuild/libs/startrack-1.9.19.jar

**Comment by cbeust** [comment]
Probably a `TaskResult(false)` not being propagated, will take a look shortly.

**Comment by cbeust** [comment]
Fixed in bcc6af5f37450060850d6ee5ee0ab53196b13b1c and deployed.

**Comment by pabl0rg** [comment]
Thank you! Kobalt is more awesome by the day
